<a href="https://colab.research.google.com/github/audreychela/Audrey_first_repo/blob/main/Data_cleaning_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**AVIATIONDATA CLEANING WITH PANDAS.**

1. **Overview**


The AviationData dataset contains historical records of aviation accidents and incidents reported from 1962 to 2023. It includes detailed information such as the date and location of the accident, aircraft type, operator, level of damage, number of injuries or fatalities and weather conditions.

The aim of this project is to clean and prepare the dataset for meaningful analysis, with the ultimate goal of uncovering trends, improving safety insights, and guiding aviation stakeholders in decision-making.

**1.1 Objectives**

* Understand the structure and content of  the AviationData
* Identify and handle missing, duplicated, or inconsistent data entries.
* Ensure data quality through standardization and type conversion.
* To perfom Explolatory Data Analysis to show safety-related insights.
* Explore historical trends in aviation accidents
* Perform Exploratory Data Analysis (EDA) to draw safety-related insights.

**1.3 DATA UNDERSTANDING.**

The dataset includes both structured (e.g., dates, numerical counts) and semi-structured fields (e.g., location descriptions, aircraft type). Initial inspection using commands like df.info(), df.describe(), and df.head() can help assess:

1.   Number and type of columns
2.   Number of records (rows)
3.   Presence of null/missing values
4.   Data types  such as; object, int, float
5.   Ranges for date and numerical values

1. **IMPORTING RELEVANT LIBRARIES.**

Import the pandas library using the standard alias pd.

In [46]:
# Import pandas with the standard alias.
import pandas as pd

2. **Loading Data into a DataFrame Called AviationData.csv and getting information**

The file path is AviationData.csv. I will use pandas to read in the data from this CSV file and create a dataframe named df.

In [47]:
#loading dataset and assigning it as df
df = pd.read_csv('AviationData.csv', encoding = 'latin1')

/tmp/ipython-input-47-1084618488.py:2: DtypeWarning: Columns (6,7,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('AviationData.csv', encoding = 'latin1')

In [48]:
#displaying the first rows of the DataFrame
df.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

In [49]:
#displaying the last rows in the DataFrame
df.tail()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
88884,20221227106491,Accident,ERA23LA093,2022-12-26,"Annapolis, MD",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,1.0,0.0,0.0,NaN,NaN,NaN,29-12-2022
88885,20221227106494,Accident,ERA23LA095,2022-12-26,"Hampton, NH",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88886,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022
88887,20221227106498,Accident,WPR23LA076,2022-12-26,"Morgan, UT",United States,NaN,NaN,NaN,NaN,...,Personal,MC CESSNA 210N LLC,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88888,20221230106513,Accident,ERA23LA097,2022-12-29,"Athens, GA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,1.0,0.0,1.0,NaN,NaN,NaN,30-12-2022

In [50]:
#checking the dataset shape
df.shape

(88889, 31)

In [51]:
#checking the dataset information
df.info() #(verbose= False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88889 entries, 0 to 88888
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                88889 non-null  object
 1   Investigation.Type      88889 non-null  object
 2   Accident.Number         88889 non-null  object
 3   Event.Date              88889 non-null  object
 4   Location                88837 non-null  object
 5   Country                 88663 non-null  object
 6   Latitude                34382 non-null  object
 7   Longitude               34373 non-null  object
 8   Airport.Code            50132 non-null  object
 9   Airport.Name            52704 non-null  object
 10  Injury.Severity         87889 non-null  object
 11  Aircraft.damage         85695 non-null  object
 12  Aircraft.Category       32287 non-null  object
 13  Registration.Number     87507 non-null  object
 14  Make                    88826 non-null  object
 15  Model                   88797 non-null  object
 16  Amateur.Built           88787 non-null  object
 17  Number.of.Engines       82805 non-null  float64
 18  Engine.Type             81793 non-null  object
 19  FAR.Description         32023 non-null  object
 20  Schedule                12582 non-null  object
 21  Purpose.of.flight       82697 non-null  object
 22  Air.carrier             16648 non-null  object
 23  Total.Fatal.Injuries    77488 non-null  float64
 24  Total.Serious.Injuries  76379 non-null  float64
 25  Total.Minor.Injuries    76956 non-null  float64
 26  Total.Uninjured         82977 non-null  float64
 27  Weather.Condition       84397 non-null  object
 28  Broad.phase.of.flight   61724 non-null  object
 29  Report.Status           82505 non-null  object
 30  Publication.Date        75118 non-null  object
dtypes: float64(5), object(26)
memory usage: 21.0+ MB

In [52]:
#checking the info 2
df.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88889 entries, 0 to 88888
Columns: 31 entries, Event.Id to Publication.Date
dtypes: float64(5), object(26)
memory usage: 21.0+ MB

In [53]:
#checking the consise statistics summary
df.describe()

,Number.of.Engines,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured
count,82805.000000,77488.000000,76379.000000,76956.000000,82977.000000
mean,1.146585,0.647855,0.279881,0.357061,5.325440
std,0.446510,5.485960,1.544084,2.235625,27.913634
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,1.000000
75%,1.000000,0.000000,0.000000,0.000000,2.000000
max,8.000000,349.000000,161.000000,380.000000,699.000000

In [54]:
#Describing the categorical features
df.describe(include="O").T

                       count unique             top   freq
Event.Id               88889  87951  20001214X45071      3
Investigation.Type     88889      2        Accident  85015
Accident.Number        88889  88863      WPR23LA045      2
Event.Date             88889  14782      1982-05-16     25
Location               88837  27758   ANCHORAGE, AK    434
Country                88663    219   United States  82248
Latitude               34382  25592         332739N     19
Longitude              34373  27156        0112457W     24
Airport.Code           50132  10374            NONE   1488
Airport.Name           52704  24870         Private    240
Injury.Severity        87889    109       Non-Fatal  67357
Aircraft.damage        85695      4     Substantial  64148
Aircraft.Category      32287     15        Airplane  27617
Registration.Number    87507  79104            NONE    344
Make                   88826   8237          Cessna  22227
Model                  88797  12318             152   2367
Amateur.Built          88787      2              No  80312
Engine.Type            81793     12   Reciprocating  69530
FAR.Description        32023     31             091  18221
Schedule               12582      3            NSCH   4474
Purpose.of.flight      82697     26        Personal  49448
Air.carrier            16648  13590           Pilot    258
Weather.Condition      84397      4             VMC  77303
Broad.phase.of.flight  61724     12         Landing  15428
Report.Status          82505  17074  Probable Cause  61754
Publication.Date       75118   2924      25-09-2020  17019

**2.DATA CLEANING.**
Includes the folowing:

1. Checking the columns and changing mispelled to correct names
2. Checking missing values
3. Checking for duplicates
4. Checking for outliers

**2.1. Checking the columns and dealing with mispelled columns**

In [57]:
#checking columns
df.columns

Index(['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date',
       'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code',
       'Airport.Name', 'Injury.Severity', 'Aircraft.damage',
       'Aircraft.Category', 'Registration.Number', 'Make', 'Model',
       'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description',
       'Schedule', 'Purpose.of.flight', 'Air.carrier', 'Total.Fatal.Injuries',
       'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured',
       'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status',
       'Publication.Date'],
      dtype='object')

In [56]:
#checking on missing value
df.isnull().sum()

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                     52
Country                     226
Latitude                  54507
Longitude                 54516
Airport.Code              38757
Airport.Name              36185
Injury.Severity            1000
Aircraft.damage            3194
Aircraft.Category         56602
Registration.Number        1382
Make                         63
Model                        92
Amateur.Built               102
Number.of.Engines          6084
Engine.Type                7096
FAR.Description           56866
Schedule                  76307
Purpose.of.flight          6192
Air.carrier               72241
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured            5912
Weather.Condition          4492
Broad.phase.of.flight     27165
Report.Status              6384
Publication.Date          13771
dtype: int64